name: Validate Reports on Push

on:
    push:
    pull_request:

jobs:
    validate-reports:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure permission
              run: chmod 777 ./.github/scripts/validator_linux

            - name: Validate reports
              run: ./.github/scripts/validator_linux
